# Generated by Django 4.2.7 on 2025-04-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
    ]
