# Generated by Django 4.2.7 on 2025-04-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_reason_field_clean'),
    ]

    operations = [
    ]
